// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBHorIdwIHAxmxEAQ11e5-6q8rGmFKYN4',
    appId: '1:168429830337:web:47180d6665ff0211a51440',
    messagingSenderId: '168429830337',
    projectId: 'bakroon-oday',
    authDomain: 'bakroon-oday.firebaseapp.com',
    storageBucket: 'bakroon-oday.firebasestorage.app',
    measurementId: 'G-4HE4GWJBSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADI5G1OQCDI0ddaX7OKSBczdC81tps1AI',
    appId: '1:168429830337:android:ce6d98a62e62cabca51440',
    messagingSenderId: '168429830337',
    projectId: 'bakroon-oday',
    storageBucket: 'bakroon-oday.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsZ6FvTy22LdvcLjN0f2Ln-meyxwE6wa8',
    appId: '1:168429830337:ios:797dcfa6f63ca66da51440',
    messagingSenderId: '168429830337',
    projectId: 'bakroon-oday',
    storageBucket: 'bakroon-oday.firebasestorage.app',
    iosBundleId: 'com.example.restmnu',
  );
}
